### ISSUE TITLE
Opencontrail web ui did not start

### ISSUE THREAD

**Issue by jouidaR** [zioc/contrail-devstack-plugin#20] opened 2016-08-25 14:22 UTC
Hello,
I ran the script which ended up well but when connecting to the user interface on https://myip:8143 or http://myip:8080, I just got "Cannot get /".
As there weren't any processes listning on those ports, I tried to run scripts located in /opt/stack/contrail/contrail-web-core which ran nodejs. But I still cannot get to the ui.

Could you help me with that?

thanks in advance,

**Comment by raviprasad239** [comment] 2016-08-26 06:04
I also observed this with latest master branch. 
However few weeks back, it was working for me.
May be some recent merges are causing this.

**Comment by jouidaR** [comment] 2016-08-26 12:05
And did you had config and control node up? 
I also had access to the ui but didn't have the config and control nodes up: there were errors fetching data . I remerber it mentioned 'syscalls fails' !
Thank you for your reply Ravi

**Comment by derekhuang** [comment] 2016-09-01 08:56
Hi JouidaR,

I meet the same issue as yours today. Have you fixed this issue? Thanks!

**Comment by jouidaR** [comment] 2016-09-01 09:59
No actually I am facing another issue rerunning ./stack.sh !
![image](https://cloud.githubusercontent.com/assets/20801573/18163485/841d93a0-703b-11e6-9226-19491a515fc0.png)

**Comment by raviprasad239** [comment] 2016-09-01 10:06
Hi JouidaR,
From error message looks like vrouter.ko build is getting failed. Might be because of kernel header files.
Are u running 3.13.0-95-generic kernel ? If Yes, kernel header files are installed  ?
You can try following commands : 
sudo apt-get upgrade linux-image-3.13.0-45-generic linux-image-extra-3.13.0-45-generic linux-headers-3.13.0-45 linux-headers-3.13.0-45-generic

Note : You have to reboot and select 3.13.0 kernel while booting. Above command is for  3.13.0-45-generic . which worked for me.

**Comment by derekhuang** [comment] 2016-09-02 08:18
I suspect this issue is caused by some bug in the routes of contrail-web-core. The static route is "/opt/stack/contrail/contrail-web-core/webroot". When we visit https://myip:8143 or http://myip:8080, it should redirect to /opt/stack/contrail/contrail-web-core/webroot/html/dashboard.html. 

I tried to visit https://myip:8143/html/dashboard.html, it displays the blank page which actually ends up with 404 not found error when getting "isauthenticated". If I tried to visit https://myip:8143/html/login.html, the login page can be displayed. But after I fill in the account and password and click "Sign In" button, it just returns error "Cannot POST /html/authenticate".

**Comment by zioc** [comment] 2016-09-02 08:25
Could you try to re-issue "make dev-env REPO=webController" command in /opt/stack/contrail/contrail-web-core ? And then restart webserver.

I tested it on master yesterdary, and it only seems to work on second run... I didn't manage to figure out why it doesn't work on first run for now...

**Comment by derekhuang** [comment] 2016-09-02 08:35
Hi zioc, yes, it works!! From the screen log, I find the difference for second run is the static files are registered successfully, while it failed in the first run. Not sure the root cause. Anyway, Thank you so much!

**Comment by jouidaR** [comment] 2016-09-02 09:24
Hi all, 
I am trying to reinstall it and test the solution you gave. 
derekhuang, I installed the 3.13.0 kernel version as you told me and when running ./stack.sh, I am having another error (which I saw even yesterday) 
![image](https://cloud.githubusercontent.com/assets/20801573/18199253/c4ce2d5a-70ff-11e6-85c7-911b8dc0da52.png)


Any ideas? 
Thank you so much for your reactivity !!

**Comment by zioc** [comment] 2016-09-02 13:01
@jouidaR: Yes, contrail doen't officially supports mitaka for now, see https://github.com/zioc/contrail-devstack-plugin/issues/8 for, the fix.

I was actually about to update README and provide some samples to ease initial setup.

@jouidaR: This issue should be fixed by this [commit](https://github.com/zioc/contrail-devstack-plugin/commit/bfa5aaa50990a50fda36cca29f9e0451a52ef0d3), i'll close this issue.

**Closed by zioc** 2016-09-02 13:01 UTC

**Comment by jouidaR** [comment] 2016-09-02 13:05
Ok @zioc  thank you very much for your availability !!
